### ISSUE TITLE
Modifications to existing Jupyter binder

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#10]
- [x] Suppress all logs other than user generated and critical error ones.
- [x] Log traversal path

**Comment by IanMayo** [comment]
@rnllv  - could you explain this in a little more detail please?  Which notebook are you referring to?

**Comment by rnllv** [comment]
@IanMayo, I was referring to [this file.](https://github.com/DeepBlueCLtd/LegacyMan/blob/main/notebook/alpha.ipynb)

This is the log it generates.

![image](https://user-images.githubusercontent.com/77854924/205103020-5564319e-f234-4a53-9916-c73c075d8f26.png)

**Comment by rnllv** [comment]
We had planned to build and test our parser from this notebook.

**Comment by IanMayo** [comment]
Oops, closed by accident.

**Comment by rnllv** [comment]
Closing, as this will be replaced by `Beautiful Soup`.
