### ISSUE TITLE
Properties of class/unit

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#100]
Class/unit should have the following properties.

* Designator
* Power
* Boost Blade
* Reduction Ratio
* MAX TRPM
* Shaft Blade
* MTBF
* BHP
* AV Temp
* Max SRPM
* remarks

@IanMayo, the [DataBrowser project](https://github.com/DeepBlueCLtd/DataBrowser/issues/1#issue-1429993848) had the following properties for Class/Unit for which I need your help to map to the contents in HTML.

* main_propulsion_type
*  backup_propulsion
* max_speed
* tpk

Also, where do we map these class/unit properties in the HTML source?

![image](https://user-images.githubusercontent.com/77854924/215281536-7363c89e-f84b-4220-b277-b837f1ead41a.png)

![image](https://user-images.githubusercontent.com/77854924/215282012-3f16df29-8938-451c-b1c2-5bcb510e9e24.png)

Country should have 
* Flag.

**Comment by IanMayo** [comment]
Yes, these structures require clarification.

After stakeholder endorsement, switch to attribute names in data.

**Comment by IanMayo** [comment]
Ok, we have this data in three places:
1.  `Propulsion Table` within `Propulsion` class page
2. Within `Summary Table` at top of class page
3. Within `class summary` on a country/category page.

For the above listing, the items are listed in descending order of provenance. 

They are listed in ascending order of `likely to be present in the data`.  I _think_ we process them in reverse order in the parser, so we can handle that provenance by just overwriting the previous value of a field.

The tables are also listed in ascending order of how predictable the layout will be.  There can be quite a lot of variety in the `Propulsion Table`, according to what type of platform it is.

The `class summary` columns are the same as those present in our mock data for a country.

**Comment by rnllv** [comment]
> I think we process them in reverse order in the parser, so we can handle that provenance by just overwriting the previous value of a field.

Got it. Just like how  we treat class attributes in `Tonals` section.

>The tables are also listed in ascending order of how predictable the layout will be. There can be quite a lot of variety in the Propulsion Table, according to what type of platform it is.

Does our mock cover this?

**Comment by IanMayo** [comment]
> Does our mock cover this?

Yes. Unit A of France.  Propulsion Table:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/c9d00c87-0560-48bf-bc9a-54866e6ee02f)


Class summary:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/ba0472f3-521c-4016-aeb1-3a8f40322989)


Country summary:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/6297a665-155e-4786-9542-8e8d1c154426)

**Comment by rnllv** [comment]
Execution steps:

1) Finalize the attributes of class/unit based on the three tables (Country Summary, Class Summary, and Propulsion System). It'll be a union of properties from all these 3 tables.
2) Define a class object that can hold three sets of (similar) attributes
3) Change class parser such that attribute values are derived based on multiple matching headers instead of index positions for Propulsion System. Index positions are consistent only for Class and Country summary. Do this for tonal attributes as well.
4) Read "Class Summary" table and extract class attributes. (Other two tables are already being read)
5) Process the class (as defined in step 1) to create the class required to be exported to DataBrowser. This will be the provenance processor.

**Comment by IanMayo** [comment]
> based on headers

Sadly, that's not quite the case.  For Country Summary and Class Summary the cell contents are predictable.  Note: that in `Class Summary` there may even be some variety in the labels - though the contents are consistent.

It's the Propulsion System table where we need to allocate according to headers.  We may end up with some lookup tables to allow for slight variance in the labels provided.

**Comment by rnllv** [comment]
>Sadly, that's not quite the case. For Country Summary and Class Summary the cell contents are predictable. Note: that in Class Summary there may even be some variety in the labels - though the contents are consistent.

Ahh okay, then we'll stick with index based retrievals for Country and Class summaries.

>It's the Propulsion System table where we need to allocate according to headers. We may end up with some lookup tables to allow for slight variance in the labels provided.

Yep, will work on header based retrieval for Propulsion Systems. Right now this uses the same index based retrieval as used for Class and Country summary.

**Comment by rnllv** [comment]
1. Finalize the attributes of class/unit based on the three tables (Country Summary, Class Summary, and Propulsion System). It'll be a union of properties from all these 3 tables.

@IanMayo, this will be finalized attributes of unit/classes. Please check if you want to modify the names on any `Finalized Attribute`

**Note:** live document to hold this data available [here](https://docs.google.com/document/d/1j196NlCB9WtSdpd7ZwOIqc0MdYQFcqD_621PiSDI2R0/edit?usp=sharing)

| Finalized Attribute | Reference in Propulsion System | Reference in Class Summary | Reference in Country Summary |
|-|-|-|-|
|**Cruise Plant**|Cruise Plant, Propulsion|Drive|Propulsion|
|**Boost Plant**|Boost Plant|*N. A.*|*N. A.*|
|**Reduction Ratio**|Reduction Ratio|R:R|Reduction Ratio|
|**Max TRPM**|Max TRPM|*N. A.*|*N. A.*|
|**Shaft X Blade**|Shaft X Blade|Shaft X Blade|Shaft X Blade|
|**Range**|Range|*N. A.*|*N. A.*|
|**Max. Speed**|Max. Speed|Max. Speed|Max. Speed|
|**Av. TPK**|Av. TPK|Av. TPK (Guide)|Av. TPK|
|**Max. SRPM**|Max. SRPM|*N. A.*|*N. A.*|
|**Mode**|*N. A.*|Mode|*N. A.*|
|**Designator**|*N. A.*|*N. A.*|Designator|

**Comment by IanMayo** [comment]
I _don't think_ TRPM is a concept. Will check onsite.

**Comment by rnllv** [comment]
Execution steps:

2. Define a class object that can hold three sets of (similar) attributes **[In Progress]**

**Comment by IanMayo** [comment]
Defer this, now that we're pursuing alternate strategy

**Comment by IanMayo** [comment]
Defer this level of analysis for a future phase
