### ISSUE TITLE
Parsing "non-standard" entities

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#103]
Kindly confirm the following for "non-standard" entities.

* Are these always going to be countries? In other words, are these entities at the same level as the countries in other "Regions"?
* What "region" should these non-standard entities be assigned?

**Comment by IanMayo** [comment]
For now, yes - they are Countries.  For now, let's put each one inside a Region of the same name as the Country.  So, we'll have "Britain" in "Britain".  

I know that looks weird - but the app is targeted at British users, and their train of thought will allow for "Britain" to be a special case in this way.

**Comment by rnllv** [comment]
Got it.
