### ISSUE TITLE
Extracting sub-type information from non-standard coutries

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#105]
From analysing the only available non-standard country page, I see the below approaches to extract sub-type text.

* From the href in the listing available in the non-standard country page: Split the name of the html file **Britain_Complex.html** to extract the sub-type text.
```
<h1>Britain Overview Page</h1>
<div><a href='../Britain_Complex/Britain_Complex.html'><img src="../Britain_Complex/Content/Images/unit_da.jpg"> </a></div>
<div><a href='../Britain_Standalones/Britain_Standalones.html'><img src="../Britain_Standalones/Content/Images/unit_da.jpg"> </a></div>
<div><a href='../Britain_Composite/Britain_Composites.html'><img src="../Britain_Composite/Content/Images/unit_da.jpg"> </a></div>
<div><a href='../Britain_Legacy/Britain_Legacy.html'><img src="../Britain_Legacy/Content/Images/unit_da.jpg"> </a></div>
```
* From the table header description data in each sub-type page
![image](https://user-images.githubusercontent.com/77854924/217848453-bd094f6c-7583-42f4-92cf-c69ba7e6f88c.png)

For now, I'll stick with approach 1, extract from html file name.

@IanMayo, I'll need both these approaches to be checked for consistency in the real data the next time you're at client site.

**Comment by IanMayo** [comment]
For the first strategy,  the URLs don't have a fully consistent naming convention.

The second strategy is the better one to take.

**Comment by rnllv** [comment]
Okay, then I'll stick with the second one.

I'll add the below assert

```
assert titleDescription starts with "Overview of " and ends with "in <Region>"
```
```

**Comment by rnllv** [comment]
We can close this. Our asserts should identify any discrepancies.
