### ISSUE TITLE
Dedicated remarks section in tonals page

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#114]
@IanMayo, I see some dedicated "REMARKS" section in tonals page. Should these be parsed and assigned to "CLASS"."REMARKS" field?

![image](https://user-images.githubusercontent.com/77854924/221911120-5ca77b4e-8d44-46f9-850a-959b7bd66beb.png)

**Comment by IanMayo** [comment]
Ho @rnllv - each of these is a remark about a single tonal.  We need to add an optional `remarks` field to tonals, and put this text into it.

**Comment by IanMayo** [comment]
Close. Should come clear once we have DITA target schema
