### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#12]
Set up the following to be tested at client system.

python project with dependencies.txt
base "hello world" module that has function that returns "hello world"
unit test called "test_hello.py", in a "test" folder to verify the above

**Comment by rnllv** [comment]
Can we close this @IanMayo?

**Comment by IanMayo** [comment]
I'll try to test it on the target network this afternoon.

**Comment by rnllv** [comment]
Got it.

**Comment by IanMayo** [comment]
Tested and working, once `Ian` managed to get command-line to open that had `pip` in the path.
