### ISSUE TITLE
Multiple h1 elements in tonals page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#128]
We wish to find the tonals table on a class page.

Our initial way of doing that was to look for the table following a `<h1>Propulsion</h1>` element.

But, that is failing, because in one class there is an unrelated table before the tonals table.

So, we need a new test.  This _looks-like_ a generic pattern:
- find all tables on the page
- extract first `td` from the first `tr`
- check if the `td` has a `colspan`, and check value of the `colspan` is `4`
- if it does, attempt to extract the tonal data from it.

**Comment by rnllv** [comment]
Next issue to be resolved after https://github.com/DeepBlueCLtd/LegacyMan/pull/137
