### ISSUE TITLE
Illegal path chars in sub_category

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#130]
When taking safe copies of image, we put the image in a folder named according to the country, category, and sub_category.

One sub-category is "LEGACY / TRADITIONAL".   The forward sloping slash is illegal for a MS-Windows page, so the parse falls over.

This issue doesn't arise on MACOS, since the `/` is a legal path character.

When we read in the `sub_category`, we should strip the value of of any `/` characters.

Breaking change _possibly_ introduced in this commit: https://github.com/DeepBlueCLtd/LegacyMan/commit/2686625a5722cf58f346a6a4d6ced3e48e8c8086

**Comment by rnllv** [comment]
The following is from #148 
>So, really need a better fix. I suspect this will be through cleaning the sub-category earlier in the parsing session.

That's right. Cleaning it early would be the better/right fix.

I think it'll be better to replace forward slash ("/") with a hyphen ("-") which will result in a better looking sub-category name than when replaced with underscore ("_")

**Comment by IanMayo** [comment]
> I think it'll be better to replace forward slash ("/") with a hyphen ("-") which will result in a better looking sub-category name than when replaced with underscore ("_")

Yes, agreed.

_Maybe_ when creating these identifiers we should all non-character identifiers (including spaces) for hyphens.

So, we will have ´industrial-legacy´ instead of ´Industrial / Legacy´ . Removing spaces does seem like a step towards being more robust.
