### ISSUE TITLE
Set the target directory from argument passed to the parser

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#133]
Right now, the value for `TARGET_DIRECTORY` variable in legacyman_parser/utils/constants.py is hardcoded.
Set it from argument and update README accordingly.

**Comment by IanMayo** [comment]
As an alternate strategy that avoids extending the command line, how about at app startup, we find the absolute path for the current working directory, append `target` to it, and store it in that global variable.

We're only doing this one big parse undertaking, we don't need lots of configurability :-)

**Comment by rnllv** [comment]
Yep, that's even better.
