### ISSUE TITLE
ns countries not shown in DataBrowser

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#168]
Data for ns countries is not shown in the Data Browser.

I see that the content is pushed to the `publication.js` document, in the `ns_country_classes` element.

I'm pretty sure this element is ignored by DataBrowser.

But, _maybe_ DataBrowser doesn't have to know about `classes` and `ns_country_classes`.  _Maybe_ we just combine them both into one classes array, and that goes into `units`.

**Comment by IanMayo** [comment]
Re-open for @rnllv .  It appears the new processing results in a failing test. The issue could be with the data, but we have to fix either the data or the code.

![image](https://user-images.githubusercontent.com/1108513/231774496-e9ed5f4c-90fb-45c6-8b88-28cb3259bae4.png)

**Comment by rnllv** [comment]
@IanMayo, I pulled the latest changes and checked. I was not able to replicate this issue in `develop` or `150_class_across_multiple_files` branches. 

Can you share the commit id with which we can replicate this?

**Comment by IanMayo** [comment]
I get the above issue when I run `python -m legacyman_parser.parser data` on `develop`.

Issue #173 is the main priority right now, but this issue _could_ be due to one unit being used for two countries.

**Comment by rnllv** [comment]
>this issue could be due to one unit being used for two countries

Yep, that's indeed the reason. In the mock data, Britain is referenced as a non-standard country as well from Europe region. I was not able to replicate this issue since the `href` in Europe was invalid due to case-sensitivity issues.

Should we expect this kind of data in real environment, where a country is there as a non-standard country as well in a region?

On a different aspect, should we further strengthen that assert to check for case-insensitive matches?

**Comment by IanMayo** [comment]
Could we extend the test to include improved diagnostics, such as listing where the class is referenced from?

I don't know the answer to how we deal with the real data - I'm going to have to do some inspection of the data, and maybe discussion(s) with the stakeholders.

**Comment by rnllv** [comment]
Okay. That assert is going to help us decide whether we can stick with regeneratable unique ids to be used as bookmarks in DataBrowser instead of integers being used now.

**Comment by IanMayo** [comment]
Yes, persistent IDs will be good, so `favourites` remain valid.

**Comment by rnllv** [comment]
>Could we extend the test to include improved diagnostics, such as listing where the class is referenced from?

Let me try. I'll print this diagnostic as part of the assert itself.

**Comment by rnllv** [comment]
We'll see if this is a valid scenario in real data, i.e. same country being referenced from different locations, or same country having two similarly named units in the same sub-category, and we'll take a call on either muting this assert or changing the data.
