### ISSUE TITLE
Tonals table comes from ns-countries

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#169]
I may be mistaken here, but...

I'm looking at the `tonals` object in the exported data.  These are the tonals from the ns-countries.   So, when the tonal refers to `unit_id` 6, it matches the content of `unit_id` 6 from the `ns-country-classes` element in JSON, not the `units` element.

This may be related to #168

**Comment by rnllv** [comment]
Tonals (as captured in TONAL_COLLECTION list) are from standard as well as non-standard classes. I'll need to change the id generation logic of classes/units as they are from two different collections. Ultimately, we'll be merging these into a single collection as described in #168.
