### ISSUE TITLE
Capture class attributes from country page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#179]
The country page contains summary data for each class.  Sometimes there is not a class-specific page, so this summary data is all we have.

There has been some _slight_ variation in the titles, but the content of the columns is certainly consisten.

There is always a TD with a colspan of 7 containing the word `PROPULSION`, then a row of headers, then a series of `colspan=7` for the `category` of the class, then one row per class.  If the first cell in the row is a link then our parser already goes off and processes that page.  The `sub-category` for the class is in the second cell (normally titled `designator`). 

Aah, hold on. There are some other `colspan=7` rows, including ones that add details for the previous row.  These don't have a `bgcolor` field.  So, the `sub-category` rows have a `tr` with `colspan=7` _AND_ a `bgcolor` attribute.

![image](https://user-images.githubusercontent.com/1108513/232092307-8139426c-2c05-4c1e-a08d-296b8d66bcdd.png)

**Comment by rnllv** [comment]
>Capture class attributes from country page

@IanMayo, correct me if my understanding is wrong but we're already capturing the class attributes from country page as part of legacyman_parser/parse_class_table.py 

>There is always a TD with a colspan of 7 containing the word PROPULSION, then a row of headers, then a series of colspan=7 for the category of the class, then one row per class. If the first cell in the row is a link then our parser already goes off and processes that page. The sub-category for the class is in the second cell (normally titled designator).

I believe you're describing the tonals page here, and not the country page. 

We're capturing attributes from tonal page as well, and updating these value, as applicable, to the class attributes as part of legacyman_parser/parse_class_attributes_from_tonals.py

**Comment by IanMayo** [comment]
You are right, I was wrong to use "propulsion" as matching term.

Will check code as soon as I can.

**Comment by IanMayo** [comment]
Aah yes - I see we are collecting the class attributes from the country page:
![image](https://user-images.githubusercontent.com/1108513/232288440-7dd43385-a987-4702-839e-733ae9c09dea.png)

Assigning to myself, to double-check it's working on the real data, because  _think_ they fields were empty in DataBrowser.

**Comment by IanMayo** [comment]
Ok. Have checked real data.  I have class for which we have Max Speed in both the country page, and in the class page.

In the exported JSON, `max_speed` is `null`.  I've just looked at the processed mock data in `LegacyMan` the max_speed fields `null` there, too.  

Aah, while it's `max_speed` in the data, that field is processed as `bhp` in the code above.  Aah, the only attribute with a value in the mock `JSON_publication.js` is the `Engine` one:
![image](https://user-images.githubusercontent.com/1108513/232827172-5af6d184-5127-4501-b0d2-33c3e5fef1a5.png)

**Comment by IanMayo** [comment]
Ok, I've found the issue @rnllv   In `json_publisher.py` we don't push the data to the output, we provide a series of `None` values to the `ClassU` constructor.
