### ISSUE TITLE
Quality check - Identify unsupported filetypes

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#18]
Supports #7

There are basically two types of files we'll be handling: text and image.  

This is to 
* identify if there are any file types other than text/image.
* ensure that the application is aware on how to process them.

**Comment by IanMayo** [comment]
It will be a useful `audit` on what files we have.

I'm also expecting:
- pdf
- excel
- _maybe_ wave

**Comment by IanMayo** [comment]
I think this will resolve itself.
