### ISSUE TITLE
Missing `data` folder in img URL for class images

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#187]
The parse is successfully completing.  We have a folder of class_images. We have `images` in the `units` data.  But, the URL for these images is wrong.  It is missing the leading `data\` folder.

I did global find/replace on "class_image" to "data/class_image" and it fixed the image URLs, and they all appeared.

I'm pretty sure this is a `LegacyMan` issue.

**Comment by rnllv** [comment]
We copy the images generated in `LegacyMan` to the `images` directory. PR #204 raised.

**Comment by IanMayo** [comment]
Verify onsite

**Comment by IanMayo** [comment]
No, the issue is still present.

In the parser, we copy the images to `target\class_images\country\platform_type\platfomrm_subtype\original_image_name`.

To deploy the published app, I copy the contents of `target` (js and two folders) to the `data` folder in `DataBrowser`.

But, in the `units` block of the published js, the  URL for image entries starts with `images/class_images/xxxx`.

It should be `data/class_images/xxx`.

I see that `images/class_images` is where we put the mock image data for the previous auto-generated data.

**Comment by rnllv** [comment]
@IanMayo, I believe there has been some misunderstanding on the target directories to be used.

At the parser application [LegacyMan], the class and flag images are copied to `target/class_images` and `target/flags` directories. The publication json is created in `target` directory.

To use the same images and json in the browser application [DataBrowser], the following copy operations are to be performed from LegacyMan to DataBrowser folder.

* Copy json file
`cp ../LegacyMan/target/json_publication.js ../DataBrowser/public/data/publication.js`

* Copy class images
`cp -r ../LegacyMan/target/class_images ../DataBrowser/public/images`

* Copy flag images
`cp -r ../LegacyMan/target/flags ../DataBrowser/public/images`

As shown above, the json and images are expected to be copied in two different target directories.

But, I see your point of having a simple copy operation. Let me work on that.
