### ISSUE TITLE
Class page links to page of images

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#189]
For some class pages, there are just low res images of that class. Each links to a hi-res version.  Unuckily, they don't link to the image file.  They link to an anchor on the page containing the image file.  No the anchor isn't adjacent to the image - it's in a `div` that uses absolute CSS positioning to put it next to the image.  I _guess_ the best we can do is that when this happens, navigate to the images page, and handle all images.

Aah, but...  The image may be part of the `Propulsion` block.  So, first process the propulsion block (including images), then exclude these images from the class-level import.

Ian to produce a demo/mock of this pattern

**Comment by metapercept** [comment]
Images will be implemented using img >imgsrc in DITA elements.

**Comment by IanMayo** [comment]
Superceded by #233
