### ISSUE TITLE
Need two tiers of type

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#206]
In our information architecture we have two tiers of type, type and sub-type.

But, in our mock data there is just one.

We need to introduce mock data that uses both tiers of type.

- Country
- Category (opt)
- Summary page, broken down by sub-category

So, for some nations an index page breaks them down by `type` (truck/car/bike).  The for all nations the summary page breaks them down by sub-type.  Within each sub-type are a list of classes of that sub-type.  The `designator` column in the summary page may offer an even lower level of categorisation.

Here is an imaginary structure for `France`.  These headings are not specific to `France`, but generic across all installation types.  It's the items within these sub-categories (classes) which are specific to the nation.

```
- Truck
    - Articulated
    - Refigerated
    - Car Transporter 
- Car
    - Saloon
    - Station wagon
    - Convertible 
- Bike
    - Mountain
    - Road
    - Leisure 
```

Sadly there is some inconsistency in the data. For a nation with only a few classes, they may just be broken down into `Truck/Car/Bike`.  For larger nations they may have `Truck/Car/Bike` at a top level, then on the dedicated `Truck` page, have the items `Articulated/Refrigerated/Car Transporter`.   Even more sadly, sometimes they `Truck` then list of `Truck` classes then `Saloon` and saloon classes, and `Station Wagon` and a list of station wagon classes.  So, the table is broken down by unstructured sequence of `type` and `sub-type` headings in the same list :-(

**Comment by rnllv** [comment]
@IanMayo, we already have the data as per [this comment](https://github.com/DeepBlueCLtd/LegacyMan/issues/32#issuecomment-1508823687). Please correct me if I'm wrong.

**Comment by IanMayo** [comment]
Defer this, it's not relevant to the current strategy

**Comment by IanMayo** [comment]
Handled, I think,.
