### ISSUE TITLE
7 column tonal table

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#212]
Oh great.  I have just encountered a 7 column tonal table.

We should reproduce it in our data, and check we handle it.

There is now data in `develop` that reproduces the layout. We should update our parser to read it, and include that in a test.

I've just looked at our code, and _maybe_ it's not important. We just need to test that.

**Comment by rnllv** [comment]
Some unrelated asserts are failing as part of the recent merges. Checking further.

**Comment by rnllv** [comment]
Issue looks to be file data/Britain_Complex/unit_daf.html (moved from data/Britain/unit_da.html as part of 12744c0) referring to non-existent flag images as part of 67c271a6. Will be adding images as required to resolve the below assert error.

```
AssertionError: InvalidAssumption: Class image file exists if provided in img attribute. data/Britain_Complex/Content/Images/FlagS.jpg not found as specified in data/Britain_Complex/unit_daf.html.

```
