### ISSUE TITLE
Cleanse ref-ids 

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#222]
Cleanse ref ids by substituting special characters in them.

|Special Character|Substitute with|
|-|-|
|*|`To be removed`|
|'|`To be removed`|
|/|-|
|\\ |-|
|(|-|
|)|-|
|`|`To be removed`|
|&|-|

**Comment by IanMayo** [comment]
Given all the chars from other alphabets, I think that any chars other than a-z, 0-9, -, _ that don´t get replaced as listed above, should be stripped from the id.

**Comment by IanMayo** [comment]
I've spotted another change. We should collapse multiple consecutive spaces down to one.  There are occasions when spaces are inserted to help with formatting - but they make our IDs look silly.

**Comment by rnllv** [comment]
@IanMayo, I believe this is already taken care of in the code. Do we have ids generated with consecutive spaces?

```
>>> import re
>>> valid_characters_pattern = re.compile('[^0-9a-z_-]+')
>>> re.sub(valid_characters_pattern, '', 'This    is')
'hisis'
>>> re.sub(valid_characters_pattern, '', 'his    is')
'hisis'
>>> 
```

**Comment by rnllv** [comment]
As per the pattern, all instances of one (or consecutive) illegal characters will be removed.

**Comment by IanMayo** [comment]
In `publication.js`, I'm in the `units` array, I have an item with a `ref_id` like: `france-legacy-barney_____________-type-12-_`

I can only presume the list of underscores are from spaces in the name in the text (used in this case to ensure the second line aligns properly).

This is in a country summary page, and the html looks like this:
```
<TD><a href="unit_a.html"><strong>Barney</strong></a><span style="color: #f00;">*</span><br>
             (Type 12) </TD>
```

Note: there are 10 underlines in the `ref_id`, and there are 10 spaces at the start of the second line above.  Our code does successfully strip out the asterisk.
