### ISSUE TITLE
Command to publish `index.ditamap` to XHTML5 using DITA-OT

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#260]
I'd like the last step in our process (if it successfully completes) is to publish the `target\dita\index.ditamp` using the DITA=OT library.

We would specify that the output goes to `target\html`, and publish using the DITA Map XHTML template.

The output of this task will be a command that can be run from the root of the `LegacyMan` repo.

The command can be provided as a comment in this issue.

**Comment by brahnavank** [comment]
`$DITA_OT/bin/dita --format=html5 --input=index.ditamap --output=target/html`

**Comment by IanMayo** [comment]
Thanks for that @brahnavank 

Is there a parameter to specify the target directory?  We'd like it to go into `target/html`.

**Comment by brahnavank** [comment]
--output=dir

**Comment by IanMayo** [comment]
Done. Working
