### ISSUE TITLE
Copy ditamap to destination

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#262]
In the `data` folder is an `index.ditamap` this is the `root` of the new document.

1. force delete any folder called `target` in the current folder
2. create a folder called `target` in the current folder
3. copy `index.ditamap` and `welcome.dita`  from `data` to `target/dita`
4. run the [command](https://github.com/DeepBlueCLtd/LegacyMan/issues/260) to export the ditamap to html.  Note: you'll have to download DITA-OT, and declare it's root folder as a DITA_OT environment variable  on your machine (note the switch from hyphen to underscore, hyphens don't work in env variables on mac/linux). I'm using version 3.7.4.
5. you will also need to have Java installed on your machine.
6. Insert a line in the console logging to report `Publish complete after xxx seconds. Root file at xxx\xxx\xxx`.  This will come after `parse complete` entry.

Note: for the output of this task, I'm expecting:
* an updated `parser.parser
* the `index,ditamap` and `welcome.dita`  in `data`
* a `target` folder that just contains the copied `index.ditamap` in the `target/dita` folder
* the published content in `target/html`.  No, it's not great to put generated content into version control, but it's a quick way for me to review/verify what has changed from the previous publish.

**Comment by ebenezer-melkamu** [comment]
@IanMayo are you sure there is an `index.ditmap` file in the `data` folder? because i can't seem to find it

**Comment by IanMayo** [comment]
The publish command is failing with the current ditamap, because of missing files.

Here is a ditamap and a welcome page that you can copy into `data`, and they publish correctly:

[initial dita content.zip](https://github.com/DeepBlueCLtd/LegacyMan/files/12111688/initial.dita.content.zip)

**Comment by IanMayo** [comment]
Also note: with the above initial content, this command just ran for me:
```
$DITA_OT/bin/dita --input=target/dita/index.ditamap --output=target/html --format=html5

```
