### ISSUE TITLE
Demonstrate install/usage of DITA Validator

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#271]
There is a DITA Validator here: https://jason-fox.github.io/dita-ot-plugins/validate.svrl/

Our `dita` publish commands performs some validation, but I believe the above plugin would further improve the content/quality of the `.dita` files we produce.

This task is to create a series of comments in this issue that show how to install/run `DITA Validator` on the `target/dita/index.ditamap` in our `LegacyMan` repo.  The comments will include command line instructions and screenshots showing how to install and run the validator, plus what @brahnavank thinks could be useful customisations of the valdiator.

**Update** Ian to do test-run on his dev machine. If successful modify repo welcome to include configuring the validator.

**Comment by brahnavank** [comment]
Install plugin
`dita install https://github.com/jason-fox/com.here.validate.svrl/archive/master.zip`

Validate and generate report
`./dita --format svrl --args.validate.mode=report --output out --input /LegacyMan-develop/target/dita/index.ditamap`

Validate and output commandline

`./dita --format svrl --input /LegacyMan-develop/target/dita/index.ditamap`

**Comment by IanMayo** [comment]
@brahnavank ran the command and got this output:
```
[ERROR] [/welcome.dita]
 Line 4: topic[id="links_1"] - [id-not-lower-case] 
The ID value in id="links_1" is invalid, allowed characters are: lowercase, a-z only, words separated by hyphens.
[WARN] [/welcome.dita]
 Line 4: topic[id="links_1"] - [topic-file-mismatch] 
The value specified in id="links_1" does not match the file name: welcome.dita. Make sure the ID value and the file name are the same.
[ERROR] [/regions/regions.dita]
 Line 5: topic[id="links_1"] - [id-not-lower-case] 
The ID value in id="links_1" is invalid, allowed characters are: lowercase, a-z only, words separated by hyphens.
[WARN] [/regions/regions.dita]
 Line 5: topic[id="links_1"] - [topic-file-mismatch] 
The value specified in id="links_1" does not match the file name: regions.dita. Make sure the ID value and the file name are the same.
[ERROR] [/regions/regions.dita]
 Line 9: image - [image-file-type-not-supported] 
The value provided in href="./content/images/world-map.gif" specifies an unsupported file format (only *.jpg, *.jpeg or *.png are allowed). Change the format of the linked file.
Found 3 Errors 2 Warnings
```

I thought this:
1. id format: yes, we can improve the ids
2. id does not match filename: yes, that would be an improvement
3. unsupported file type:  **brilliant** .  Well, it looks like it's supported in HTML export, but I'll convert to one of the specified formats so things are more robust

**Comment by IanMayo** [comment]
Ok, include this validation, using this command:
```
$DITA_OT/bin/dita --format svrl --input target/dita/index.ditamap 
```

**Comment by IanMayo** [comment]
Ian to get DITA_OT & validator plugin onto target network

**Comment by IanMayo** [comment]
Done.
