### ISSUE TITLE
Parse process ignoring source folder

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#277]
In the command line we can specify the source for the data.

But, we don't use that value.  The `data` sub-folder is hard-coded into the `process_regions` method.

Note: in use on the real data I use an absolute path.  So, test implementation by temporarily renaming `data` to  `data_rename`.   Check parser runs when temporary path provided.

Ian worked around this by manually editing the instances of `data/` to `e:/src/`

**Comment by ebenezer-melkamu** [comment]
@IanMayo The root path for the data folder should be this one right?

```
  source_dir = "data/PlatformData/"
```

**Comment by IanMayo** [comment]
no, it's a command-line parameter, `data` in the following:
```
python -m parser.parser data
```

**Comment by IanMayo** [comment]
So, if you temporarily rename `data` folder to `data_rename`, we'll run the import by typing:
 `python -m parser.parser data_rename`
