### ISSUE TITLE
Process files linked from the current file

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#289]
Our pages include link to related files, and sometimes to existing class files that we have already processed.

So, when we processing `htmlToDITA`, perform the following:
- look for `<a href="">link</a>` hyper links
- generate the name for the DITA version of the target HTML file
- check if that file exists. If it doesn't:
    - use "colspan:6" check to establish if it's a class page. If it is, just generate link - we'll let the class processing handle it.
    - if it's not a class file, then:
        - generate target DITA file (as `topic` type)
        - find the _content_ sections of source file
        - for each section:
            - find first heading (h1 through h5 if necessary)
            - translate content to DITA
            - push `section` to body of target file, including first heading as title
        - write file to target dita-name 
- create `<xref>` element in dita, pointing to generated file

### Finding _content_ section of target file

**Update:** `Britain_2A` files for `phase_a_xx.html` use the correct format.

The units to be processed all have this structure:
```
<div id="BottomLayer">
   <div id="PageLayer">
     <h2>Some title</h3>
     <p>Assorted content in here</p>
   </div>
</div>
<div id="BottomLayer3">
   <div id="PageLayer3">
     <h3>Some other title</h3>
     <p>More content in here</p>
   </div>
</div>
```

So, it's `PageLayerxxx` that we are looking for.  See how-to below.

```
dates = soup.findAll("div", {"id" : lambda L: L and L.startswith('PageLayer')})
```

**Comment by ebenezer-melkamu** [comment]
@IanMayo I have a function in my `class_file.py` named  `parse_propulsion`, what if i first find the `href` of the other file and pass the `Propulsion` block to the `parse_propulsion` function?

**Comment by IanMayo** [comment]
There is logic in that suggestion.  I did consider doing it that way.  But, the linked file has a number of blocks of text, other than the `propulsion` block. That same propulsion block is also used for some other similar `class` files.
So, it makes sense to convert all of the other file, and link to it.
Note 1: we do this processing if the `parse_propulsion` fails to find the relevant named block - so it replaces the `else` in `parse_propulsion`.
Note 2: there will be other occasions when we wish to convert a set of `PageLayer` elements in `html` to `dita` (such as when we encounter an `<a>` in `htmlToDita`).  So the code to convert the file should be in a re-usable method.

Here is what I imagine this new `parseNonClassFile` method to look like:
```
    def parseNonClassFile(file_path):
        ' strip anchor off path
        ' generate DITA filename
        ' if file does not already exist:
            ' read file into soup
            ' define new DITA soup object
            ' create top level elements in target
            ' loop through elements of interest (See `Finding content section of target file` above)
               ' find heading
               ' convert to DITA
               ' append to target
        ' return DITA filename
```

**Comment by IanMayo** [comment]
Done.
