### ISSUE TITLE
Handle html content within summary and signature tables

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#292]
We are processing the summary and signature tables.

But, we are not supporting complex content within the cells (such as links, lists, etc).

So, when we are looping through the above tables, call our `htmlToDita` method for the contents of each cell, before the cells get filled in.

This is _probably_ just a change in how we fill in the contents for `dita_entry` here:

![Image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/76756c2a-3494-45cb-bd3b-a3b579e0869c)

Instead of doing `dita_entry.string = td.text.strip()` we do `dita_entry.string = htmlToDita(td.text)` (or something like that)

**Comment by ebenezer-melkamu** [comment]
@IanMayo We are processing the `signature` in the `parse_summary_and_signatures` function, can you please point me where to call the `htmlToDita` function ? becuase we already have a `for loop` that is parsing the `table` element ?

**Comment by IanMayo** [comment]
Sure.  It's the contents of each table cell that I want us to process. This should allow us to handle images or hyperlinks that could appear with table cells.  So, it's when we loop through the `<td>` elements.
