### ISSUE TITLE
Design parser for legacy content

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#3]
Consider tools/technologies to parse legacy content, and produce new version using the New Information Architecture [https://github.com/DeepBlueCLtd/Fi3ldMan/issues/2]

Ian's thoughts on sequence:
* [ ] Logic to _walk_ data tree
* [ ] Put content into new structure
* [ ] Find images, move into correct location
* [ ] Put content into correct new DITA content, in agreed location
* [ ] Unit tests to verify content from legacy goes into new version

## Observations
1. Every file I checked had a single div with an ID of "BottomLayer".  This seemed to carry the substance of the page.
2. For a `country` page, the div before the "BottomLayer" contains useful metadata:
    a. a div with id  `Title` which contains an `h2` with the country name
    b. the title div is followed by another div, which contains an image, representing the country's flag. The id of the flag div varies between "image2", "image3", etc.
3. The `BottomLayer` div contains a `PageLayer` div, which carries the content for the page.

**Comment by rnllv** [comment]
Acknowledged.

**Comment by rnllv** [comment]
Tracking phase wise items:

Phase 1:

- [x] Extract region
- [x] Extract countries (without flag images)
- [x] Extract classes
- [x] Extract tonals (without class images)

Phase 2:

- [x] Extract abbreviations
- [x] Extract multirow remarks
- [x] Extract country flags
- [x] Extract tonal/class images
- [x] Extract power details
- [ ] Process non-standard countries *[Additional testing pending as part of #39.]*

Phase 3:

- [ ] Extract transducer information *[In progress as part of #113.]*
- [ ] Extract other narratives

**Comment by IanMayo** [comment]
We're now pursuing a simpler approach. There may be a little re-working.

**Comment by IanMayo** [comment]
Close. Handled separately
