### ISSUE TITLE
Parse abbreviations page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#30]
The legacy content includes an abbreviation table [here](https://deepbluecltd.github.io/LegacyMan/data/QuickLinksData/Abbreviations.html).  We should load all of this data into _some_ structure in the DITA.

As we are publishing to HTML and/or exporting to JSON, we should provide a tooltip containing the full name for tonal sources (most of which are abbreviations).

I think the valid strategy for this is to start at the "real" introduction page (`Introduction/ContentsPage.html`) - then we can deliberately navigate to both the platform data _and_ the abbreviations data.

Hmm, actually - we can hard-code `Introduction/ContentsPage.html` - since that's the path in both the mock data and the real data.  Then we only have to pass the path to the root folder to `legacyman_parser.parser`.

**Comment by rnllv** [comment]
>we can hard-code Introduction/ContentsPage.html - since that's the path in both the mock data and the real data. Then we only have to pass the path to the root folder to legacyman_parser.parser

If this is the case, then we'll be invoking the parser command as below (without the test_payload option)

```
python3 -m legacyman_parser.parser data/

```

as opposed to 

```
python3 -m legacyman_parser.parser data/PlatformData/PD_1.html

```

Kindly confirm if `PlatformData/PD_1.html ` can be hard-coded as well.

**Comment by IanMayo** [comment]
yes, that can be hard coded.

**Comment by rnllv** [comment]
I'm proceeding with the following assumptions w.r.t. the real data.

* There's going to be only one table in `QuickLinksData/Abbreviations.html`
* Each row in this table contains two key-value pairs, side-by-side i.e. `<tr><td>Key1</td><td>Value1</td><td>Key2</td><td>Value2</td></tr>`

**Comment by IanMayo** [comment]
> I'm proceeding with the following assumptions w.r.t. the real data.
> 
> * There's going to be only one table in `QuickLinksData/Abbreviations.html`
> * Each row in this table contains two key-value pairs, side-by-side i.e. `<tr><td>Key1</td><td>Value1</td><td>Key2</td><td>Value2</td></tr>`

In the parsing code, could include tests to verify the above assumptions please?  When I _eventually_ get to run this against the real data it will be useful for LegacyMan to highlight the fact that my assumptions were mistaken.
