### ISSUE TITLE
Check if all country listings are broken down by category and sub-category

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#32]
Some mock data just has a list of classes.  That means we don't know category or sub-category.

That is probably mistaken.  Check with the real data.

**Comment by IanMayo** [comment]
Note: the mock data was broken down by category. But, because term wasn't in a `<td>`, it was displayed at the start of the table.

Yes, lists of classes are always broken down by Sub-Category. For Britain (and one other #39), there is an intermediary page where they are first broken down category.  So, it's `Category` which is optional, though I may be able to provide lookup of sub-category to category - so we can fill in the details.

**Comment by rnllv** [comment]
~~Ok, so we always have `Category`.~~

~~What about `Sub-Category` for non-British units?~~

Ok, so `Categories` will be optional and `Sub-Category` will be mandatory.

Shall we create a category called `Generic` to hold all orphaned `Sub-Categories`?

**Comment by IanMayo** [comment]
Aah, I've realised we do have this data.

In this image, "Composite" is `Category` and "PB" is `Sub-Category`.  So, we just have to move our existing `sub-category` up one level, and grab `sub-category` from `designator`.
![image](https://user-images.githubusercontent.com/1108513/232091162-0ea1c398-832d-417a-b588-41d61da2a3d8.png)

**Comment by rnllv** [comment]
@IanMayo, please mark this issue as "Ready to implement". This looks to be important.

**Comment by IanMayo** [comment]
Defer this, it's related to the previous strategy.
