### ISSUE TITLE
Verify contents of `PlatformData` directory

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#36]
Verify that `PlatformData` directory (at client's) contains only the following three types of contents.

* Content directory (which contains images)
* PD_1.html
* Individual html files representing each region.

**Comment by IanMayo** [comment]
Hmm. no. For the current phase we're ignoring quite a lot of content. 

For the current phase, we just process files that are linked to, and ignore others.

Later we'll check that _somehow_ we're handling others.

**Comment by rnllv** [comment]
>we just process files that are linked to

Got it. `href` is the bible.
