### ISSUE TITLE
Provide id for the `div` element that'll enclose the Countries table in all region page

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#37]
This is the source for Europe.html.

This page is expected to contain more than one table. It's required to identify the table which contains rows of country.
```
<html><body><div>
    lots of content
</div>
<div>
    lots of divs
</div>
<h1>Europe</h1>
<div>
<table border="1">
<tr>
<td><a href="../Narnia/Narnia1.html">Narnia</a></td>
<td><a href="../Trumpton/Trumpton1.html">Trumpton</a></td>
</tr>
<tr>
<td><a href="../Belgium1/Belgium1.html">Belgium</a></td>
<td><a href="../France/France1.html">France</a></td>
<td><a href="../Spain1/Spain.html">Spain</a></td>
</tr>
</table>
</div></body></html>
```

**Comment by IanMayo** [comment]
I've checked the data.  The countries table is the first one on the page. Other tables are to be ignored.

**Comment by rnllv** [comment]
>Other tables are to be ignored.

Now I understand  what you meant by `"validation" doesn't give us much value.`
