### ISSUE TITLE
Contents-Page first strategy

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#409]
We have started by parsing the `regions` file - that's because this is the `guts` of the document.

But, there is a lot of other content, mostly in `PageLayer` style constructs, starting with the `Introduction\ContentsPage.html`.

We should switch to `walking the tree` from this file using our generic file converter.  But when it encounters `regions.html`  adopt custom processing (our existing `regions.html` processing).

Assigning this to @IanMayo - to generate mock content for these top level pages: both for welcome and QuickLinksData pages.

**Comment by robintw** [comment]
Ok, for those general information pages, do we still want to only copy `PageLayer` divs if they are linked to from elsewhere, or do we copy the whole thing?

**Comment by IanMayo** [comment]
Ooh, that will need some (more) analysis from me.  But, I think the model of _process the first element, plus any that are the target of links_ logic is a good starting point,.

**Comment by IanMayo** [comment]
Ok.  This is in hand.
