### ISSUE TITLE
Is `image4` used twice in file A3C

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#413]
DITA is complaining because `image4` is used twice in `Phase_f.dita`.

The id is used twice in the html, see if it occurs twice in the real file, and update the mock content accordingly.

**Comment by IanMayo** [comment]
No, the id doesn't occur twice in our mock `phase_f.html` file.  It looks like a flaw in the logic - we are generating a _ghost_ div, possibly because of the image block. Transferring to @robintw

**Comment by robintw** [comment]
Fixed in #421.
