### ISSUE TITLE
Flag error if at least one `PageLayer` div instance not found in Country page

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#42]
> Arunlal: Quick question on identifying classes from country pages.
>Will these always be under `PageLayer` div?

>Ian: Yes - that's the pattern I've found.  We'll have to flag error if it doesn't exist.

It's assumed that only the first instance of `PageLayer` div will contain the table listing `units`. Others, if present, can be safely ignored.

**Comment by IanMayo** [comment]
No. If there is more than one PageLayer,  we need an to modify our  processing strategy to accommodate it. So, throw an error if a page has more than one PageLsyer.

**Comment by rnllv** [comment]
>we need an to modify our processing strategy to accommodate it.

Got it. Let me raise a dedicated issue for this.

**Comment by rnllv** [comment]
Can we close this @IanMayo? 

As per your [comments here](https://github.com/DeepBlueCLtd/LegacyMan/issues/47#issuecomment-1345191280), you'll need to come up with a strategy to identify the correct `PageLayer`, in case there are multiple, to extract the classes. And all `PageLayer's are expected to have only one table.

So, there's no need to throw error in case country pages have more than one `PageLayer`

**Comment by IanMayo** [comment]
Agreed.
