### ISSUE TITLE
Need to copy `Contents/images` folders for files that are processed

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#420]
Our parser has _escaped_ the limited subset I intended us to work on.

But, that's not a problem.  It's working quite well, with only 16 warnings.

But, there are lots of occasions when images are missing. This _seems_ to be in files that aren't in a `Britain_xx` folder.  It appears that file parsing that starts from a `category` file (Britain_legacy/Britain_legacy.html) always copies over the `content/images` content.
But, file parsing that was generated from `shopping list` does not copy the content over.

Hmm, we may end up with more intelligent processing here (such as when we process the _standard_ countries), but for now it would be convenient if the `Content/Images` folders were duplicated each time we process a file.  Aaah, but there are lots and lots of them, so let's check if it's necessary first (`Contents/Images` doesn't exist for that category.

**Comment by robintw** [comment]
Fixed in #421.
