### ISSUE TITLE
Handle targets floating in document

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#423]
Where an anchor is present in content that we are parsing, it gets converted to an id with a div.

But, on other occasions the anchor is floating on the page (such as `number2` in `phase_f.html`.

Here we need to do some `top` style processing to find the div of content that it relates to, and either change the div id to the anchor name, or insert an empty div with an id at the start of the relevant content.

**Comment by robintw** [comment]
I think this is fixed in #421, but I'd like @IanMayo to check on the real data (or anywhere else in the mock data that he sees this pattern)
