### ISSUE TITLE
Missing blocks of content in `Unit Banjo`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#425]
Looking at `unit_banjo.html`, there are 3 pages of content within the document.

We aren't processing the content of tables yet, but I think there should be 3.

See the 3 `section` elements in this DITA file:
https://github.com/DeepBlueCLtd/Fi3ldMan/blob/main/dita/regions_simple/britain/hybrid/unit_hybrid_a.dita

(This may be related to our `shopping list` logic)

**Comment by robintw** [comment]
I've fixed one part of this in #421, so we now have two parts of the file being extracted. The third part of the file is not being extracted because of the problem with the `BottomLayer` being within the `GrayLayer` - that's a separate problem I'm working on at the moment.

**Comment by robintw** [comment]
Fixed by #440
