### ISSUE TITLE
Check pattern for buttons

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#427]
Our code avoids button links by avoiding divs with an id of "btX" 

Our mock data isn't very representative, due to lots of copy/paste.

Inspect target content and establish pattern for button links.

**Update:** I see these patterns for the nav buttons:
* btn2
* btnHist2
* btnHist3
* btn
* btnHist
* btn4
* btn3

I see no _real_ div ids that begin with `btn`, though I suggest we use `btn`, `btnHist` or 4-digit id beginning with `btn` or 8 digit id beginning with `btnHist`.

**Comment by robintw** [comment]
Fixed in #433
