### ISSUE TITLE
Find example of linking to specific location in content, not at page level

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#428]
There is lots of use of linking to a specific page in the target document.

Find an instance of linking to an anchor within the content.

Check we are reproducing the pattern in mock content, and check we are handling it.

**Comment by robintw** [comment]
Is this the sort of thing you're looking for? In `Vanes&Cranes.html` there is a link to another anchor on this page, within a PageLayer:

```
<div id="image1" style="position:absolute; width:408px; height: 23px; z-index:2; left:295px; top:455px; ">
<h1>&nbsp;<a href="#number2"><strong>Click HERE for Southern Hemisphere Constants</strong></a></h1>
</div>
```

**Comment by IanMayo** [comment]
There is just one case of linking directly into content, all other links go to `page` headers.

There was an issue with the anchor being inside a heading (where DITA doesn't allow a DIV in an B), but that was fixed.
