### ISSUE TITLE
Unable to extract title for reference pages

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#431]
There are about 20 files for which we cannot find the title.  These do seem to have the `div/h2` pattern, but the `id="title"` identifier is missing.

I think we're correct to start off by looking for the div/h2 element with the known ID.  But, if it isn't found, I think we should fall back on getting any div/h2 element that has absolute positioning.

**Comment by robintw** [comment]
Fixed in #433

**Comment by IanMayo** [comment]
**Update:** There are some pages that don't have the `div > h2` construct.  As _another_ fallback, several of those I inspected do have a `<h1>` that equates to the title.  I suggest we take the contents of the first h1, and push out a warning if more than one h1 is found.

**Comment by robintw** [comment]
Fixed in #440.
