### ISSUE TITLE
Sanitized image names not found

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#435]
The DITA compiler is complaining about lots of missing images.

These are images that have had ` ` replaced with `_`.   But, when we do `copytree` we copy the images over verbatim.

So, I think we have two separate `sanitize` methods:
1.  For content file names that we control. replace ` ` with `_`
2. For images that are linked to or included, replace ` ` with `%20`

The test case for this is `daf 1b.jpg` under `anchor_pics.html`. 

We are being "sheilded" from this issue because code in extract_class_images is producing duplicates of files with spaces, replacing spaces with underscores. Well, _some_ code is putting a `daf_1b.jpeg` into the `Contents/Images` folder.

**Comment by robintw** [comment]
Fixed in #440, by changing everything to use sanitise_filename, so that we don't end up with any spaces in filenames at all. Safer that way, I think.
