### ISSUE TITLE
Generate image map in reference content

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#438]
File A17 includes an image map.

Create imagemap content in mock reference file.

Create imagemap processor in HtmlToDita.

**Comment by IanMayo** [comment]
Started in #447 

There is an `imagemap` here: https://github.com/DeepBlueCLtd/LegacyMan/pull/447/files#diff-5460138f2c0b9ffb57c301f9cf2f66bfad6016b96340b4786516b169dda7f30bR124

Here is an example of a DITA imagemap:
https://docs.oasis-open.org/dita/v1.0/langspec/imagemap.html

There is working code to generate a DITA imagemap in `Parser.py/process_regions`.  Note: that code is specific to the `regions` page, so it knows the IDs to get.  Our code will be more generic, represented in `html_to_dita`.  _Maybe_ `process-regions` can retrieve the element(s) of interest, then re-use the code in `html_to_dita`, once it's in there.

**Comment by robintw** [comment]
Is that link incorrect? It seems to go to Heroku and want me to log in?

**Comment by IanMayo** [comment]
Duh, sorry. Doing two jobs at once... Link updated.

**Comment by robintw** [comment]
Fixed in #459.
