### ISSUE TITLE
xrefs need to start with relative path reference

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#439]
We aren't processing tables, but we are processing the XREFs from the table (so we can walk the content).

OxygenXML is complaining when we have an `xref` with an href like `unit_anchors.dita`.  But, it doesn't complain when the href is specified as `./unit_anchors.dita`.

So, when we are declaring the xrefs from tables, could we please prepend `./` if there isn't already a root indicator there, or if it starts with a relative reference (hashtag)

**Comment by robintw** [comment]
Do you want this to just be the xrefs from tables? Or all xrefs?

**Comment by IanMayo** [comment]
hmm, certainly for tables.

If we do the same processing for both, then let's have both.

I guess this is an extension of "sanitize filename".

**Comment by robintw** [comment]
Fixed in #440 .
