### ISSUE TITLE
BlackList for `find first layer of content`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#446]
DITA is reporting that it some content is non-compliant (missing attributes).

But, this content should not be converted.  I think it's our logic to "import all blocks that are targets, plus the first block of content (since that block is not addressed by an anchor)".

This is picking up a "SubmitButtons" block, like this:
https://github.com/DeepBlueCLtd/LegacyMan/blob/1966774c7804c00f13d8f85804d699f57264bb91/data/Britain_Cmplx/unit_anchors.html#L16

These are the steps to find the first block of content:
- not an id with this leading text:
    - submitButtons
    - templateDetails
    - pageDetails
    - Layer
    - GrayLayer

_Hopefully_ the above will be sufficient to get to the first paragraph of legitimate content.

**Comment by robintw** [comment]
Do you mean _doesn't_ contain a table?

**Comment by IanMayo** [comment]
> Do you mean _doesn't_ contain a table?

Yes, that's what I meant.   But, I removed the line when I _hoped_ that blacklisting would be enough.

**Comment by robintw** [comment]
Fixed in #450.
