### ISSUE TITLE
Slashes in dita

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#448]
```
Unable to parse invalid href attribute "..\Britain_Complex\unit_anchors.dita"  using "../Britain_complex/unit_anchors.dita"
```

I also get similar errors when specifying the `href` for an image.

It looks like we need an `href-processor` that converts `\` to `/`.  Maybe part of `sanitiseFilename`?

Examples of this present in this commit for my current PR:
https://github.com/DeepBlueCLtd/LegacyMan/pull/447/commits/e3af83a303aa7e2e80119bef80dd283332dc1ed4

**Comment by robintw** [comment]
Fixed in #450
