### ISSUE TITLE
Found block of text that isn't processed

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#451]
The `anchor_pics.html` file includes 4th block of content (including `Warming up content`).

But, this block does not get created in `anchor_pics.dita`.

The `top` value seems to be in range of the `number4` anchor that triggers its addition to the shopping list.

Aah, in `debug` logging mode I do see that `number4` gets added to the shopping list.  It appears we don't throw an error when a matching block isn't found for `number4`.

**Comment by robintw** [comment]
Fixed in #450
