### ISSUE TITLE
Formatting a local reference

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#452]
In HTML a link to an anchor in the current page looks like this: `#number2`.

But, in DITA, the url should include the top-level topic id.  So, in a topic with ID of `VanesandCranes it's like: `#VanesandCranes/number2`

This pattern of error is (obviously) present in `Vanes&Cranes.html`

**Comment by robintw** [comment]
Ah, this was the issue that came up before in #426. According to the DITA standard, we should be using the `#ID/reference` link, but DITA-OT doesn't seem to process these correctly, and leaves them as they are in the final HTML, when we need them to actually be changed to the mangled HTML version which is `#ID__reference` - eg. `#VanesandCranes__number2`.

I suspect we may have a problem here as we're going against the DITA official standard, but it seems to be necessary to make the HTML export work.

**Comment by IanMayo** [comment]
Yes, I was just thinking the same thing.
Let me double-check Oxygen XML.

**Comment by robintw** [comment]
Fixed in #450.
