### ISSUE TITLE
Ability to run processing for just one file

### ISSUE THREAD

**Issue by robintw** [DeepBlueCLtd/LegacyMan#455]
Add the ability to pass a filename to the CLI script so that processing only runs for that file.

To do this properly we'll need to run the whole of pass 1, and then just `process_generic_file` for that file on run 2.

**Comment by IanMayo** [comment]
I _guess_ that if the above performance is still a problem we could restrict `pass-1` to the subject-file plus files that contain the filename for the subject file.

**Comment by robintw** [comment]
Fixed in #459.
