### ISSUE TITLE
Handle target folder with space

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#458]
A source file has been introduced, within a folder that contains a space:
https://github.com/DeepBlueCLtd/LegacyMan/pull/457/files#diff-0aeade354091a7ce498315d2cf3dac7459dc1b6c70f79fb28dae43ddf6cd002d

This causes this issue:
```
   [filter] file:/Users/ianmayo/git/LegacyMan/target/dita/regions/QuickLinksData/Contents_Index.dita:17:67: [DOTJ054E][ERROR]
Unable to parse invalid href attribute value "../Brush Noise/Brush_Noise.dita", using '../Brush%20Noise/Brush_Noise.dita'.
```

**Comment by robintw** [comment]
Fixed in #459
