### ISSUE TITLE
Identification of `Sub-Category` and corresponding classes in Country page - Phase 1

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#46]
We'll be using the below method to identify `Sub-Category` of classes in Country page once the `classes` table is extracted.

This is based on the visual representation of the table. 

This involves metadata hardcoding. We'll need to explicitly check for `Class` < td > column header.

We might  discard this approach if something positive comes up w.r.t.  #45 

Here's the method:
```
* Identify the table header: first < tr > which contains < td > element with innerHTML as string literal "Class" as its first child/column heading.
* Identify the `Sub-Category` header: first < tr > following table header will be the first `Sub-Category` < tr >  which might have optional < td > indicating the sub-category,  say `SC1` or `Composite` or `Legacy`. It MAY also have < strong > attribute
* Identify `Class` under this `Sub-Category`: < tr > with at least two < td > elements 
* Keep collating the `Classes` under the previously identified `Sub-Category` until reaching the next `Sub-Category` header.
```
~~* Once completed, eliminate all `Sub-Categories` without any classes. <This will take care of the `Link is to French unit_d` row>~~

These are the assumptions this approach is making:
* Table will mandatorily have table header with its first column header as text `Class` (case sensitive)
* Classes will be mandatorily grouped under `Sub-Category` (as confirmed in #32)

@IanMayo, please make corrections as necessary.

**Comment by rnllv** [comment]
Points to consider:
* Are there any tables with records that are not class records or `Sub-Category` records in the middle?
* Are there tables without headers?
* Do all the `Class` tables have the same set of column headers?

**Comment by IanMayo** [comment]
Its not feasible to inspect every page.

So, we have to use "trust but verify". We'll make an assumption about the structure, but test that assumption. When the assumption is wrong, we'll have to do one of:
- change how we do the processing, with a new assumption
- change the content, to be consistent with the assumption

**Comment by rnllv** [comment]
Got it.

Then we'll implement the `method` described here knowing full well that it will evolve.

**Comment by rnllv** [comment]
This can be closed as any changes to class/subcategory extraction can be tracked via new issues.
