### ISSUE TITLE
Table columns

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#461]
This doesn't get reported by DITA publish or validate, but it is reported in XML Editor:

![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/1381609d-06b9-4062-8c1c-577b188db375)

The same column can't be the end of one and the start of another span - the subsequent column ids need to be incremented. 

This is valid:

![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/b330e0f4-8ec5-446f-be96-d3203df3557c)

**Comment by robintw** [comment]
Fixed in #464
