### ISSUE TITLE
Folder case changes when it contains period character

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#462]
I've renamed the `Britain_Legacy` folder to `Britain.Legacy` in my PR.

Now, when the target folder is generated it is called `Britain.legacy` (`L` is now lower case).

This breaks the transform.

**Comment by robintw** [comment]
I think this is fixed in #464. It fixes the case being changed, but I can't actually reproduce the original error on my machine (I think it is a Mac/Windows difference). Anyway, this _should_ work.
