### ISSUE TITLE
Not converting local link to DITA XREF format

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#465]
The file `unit_delta(12).html` has a QuickLink to the local `Remarks` block, with id `number3`.

```
  <td width="18%" align="center"><a href="#number3">Remarks</a></td>
```

When we collate the list of related pages in DITA, this href remains the same:

```
		<link format="" href="#number3">
			<linktext>Remarks</linktext>
		</link>
```

But, it should be converted to DITA format, oh and with `format` removed:
```
		<link href="#unit_delta12/number3">
			<linktext>Remarks</linktext>
		</link>
```

**Comment by robintw** [comment]
Fixed in #464
