### ISSUE TITLE
Table Converter - borders

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#466]
I think we're missing a table attribute. It means the top and left borders of the below table are missing.  I think in other cases the left and right borders are missing/

If there is a `border="1"` in the table definition in HTML, we have to include a `frame="all"` in the DITA markup, please.

Spec for `frame` linked from here:
https://docs.oasis-open.org/dita/v1.0/langspec/table.html

![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/d63d2cce-b36a-49e1-82cf-0198e4603606)

This is what the fixed version of `unit_anchors.dita` looks like:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/8cce0568-25f0-460c-82af-e2643129face)

**Comment by robintw** [comment]
Fixed in #467
