### ISSUE TITLE
Need to walk "Standard" regions/countries.

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#469]
We currently walk the tree starting with non-standard countries (those that include an image table).

The `regions` image map only has workable links for the NS regions.  Other regions link back to the current page.

We need to start correctly processing standard regions and countries - in order to provide the country and category pages for those countries (even though we probably process class files for most of those countries).

Aah, - it probably needs me to generate sample content for non-standard countries, too :-D

**Comment by robintw** [comment]
Hopefully fixed in #474, will leave this open until we've confirmed the fix works.

**Comment by robintw** [comment]
I think we're doing this fine now - please re-open if I'm wrong.

**Comment by IanMayo** [comment]
Re-open, to keep it on my to-do list, and ensure testing this doesn't fall through the cracks.

**Comment by IanMayo** [comment]
Yes, this functionality is working perfectly.
