### ISSUE TITLE
Modify class processing logic to handle multiple `PageLayers`

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#47]
Refer #42 for further details.

**Comment by rnllv** [comment]
@IanMayo, can we take it that all the tables which are bounded by `PageLayer` div in country page (like Narnia1.html) are going to be just that of `Classes`?

**Comment by IanMayo** [comment]
No. There is just one table of classes. If there is more than one PageLayer we (I) need to come up with a new way of determining which contains the classes table.

**Comment by rnllv** [comment]
Got it.

**Comment by IanMayo** [comment]
Overtaken by events
