### ISSUE TITLE
Allow for `bold` links

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#470]
HTML allows for a link to have a style attribute.  This is present in the content for some links.  The phrase that occurs is `style="font-weight: bold"`

We should make a link in our mock content be formatted in bold.

When the html to dita processor is handling `<a>` elements, it should check for the bold style attribute. If it is present, wrap anchor in a `<bold>` element.

**Comment by robintw** [comment]
Fixed in #468
