### ISSUE TITLE
Need target element label in imagemap

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#472]
The HTML image map construct allows for a label to be provided when hovering over a target in an image map.

This was originally put into an `alt` attribute in IE.  Later browsers put it into a `title` element instead.

When we generate an image map, we should retrieve the `alt` text, and use it as the contents of the `<xref>` element.

The example here includes a "Section 1" label: https://docs.oasis-open.org/dita/v1.0/langspec/imagemap.html

**Comment by robintw** [comment]
Fixed in #474.
