### ISSUE TITLE
ImageMap offset in produced DITA

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#473]
In file A7 there is an image map.

In Oxygen XML Editor we can see the "hit zones".   They are offset from the underlying image.  See if the image is being resized (somehow) in the conversion.

**Comment by robintw** [comment]
I'm intrigued by this, as I can't see how the images would be resized or the coordinates would be changed. Could you look into this next time you're on site @IanMayo?

**Comment by IanMayo** [comment]
Update: our publish process produces responsive image-maps.  So, as the page resizes the coordinates in the imagemap change to, from whole integers (original) to lengthy floating point numbers.  It must be some upstream JS that is doing this.

We should probably see if we can switch off responsive resizing for these image maps.

Hmm, maybe not. The regions image resizes satisfactorily: https://deepbluecltd.github.io/LegacyMan/target/oxygen/PlatformData/PD_1.html

**Comment by IanMayo** [comment]
Note: we don't have this issue for the world-map on the `regions` page. See what is different about that image-map, and see if it fixes the issue.  Otherwise, reproduce in mock data, and search for support.

**Comment by IanMayo** [comment]
Got it.

When the image is "declared" in the html, it is given a different width and height.  The floating polygon coordinates are relative to this width and height.

But, our translation code doesn't bring across the width and height - so we are displaying the image full-size, and the coordinates don't quite match.

I've fixed this by resizing the two background images to be the "declared" height and width.  Now, when they are displayed full-size, the coordinates align correctly.

_Sooo_ many red-herrings along the journey to discover/understand this.
