### ISSUE TITLE
New pattern in data

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#477]
Now that we're processing more countries, we have to handle a new pattern in the data.

There is a country folder, containing a country page, but the units themselves are in category specific sister folders.

It _looks-like_ we aren't trying to generate unit files when the link target is in a sister folder (though we do insert the link).  So, the publish command reports missing files:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/31a9c107-7e01-47fe-8190-7302a5983521)

**Comment by robintw** [comment]
Fixed in #479
