### ISSUE TITLE
Extracting Class images

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#48]
Should the class images array be extracted from tonals page?

**Comment by IanMayo** [comment]
not in this phase

**Comment by rnllv** [comment]
Okay. We'll keep this open.

**Comment by IanMayo** [comment]
let's close it. Unless something is an important reminder, let's not create issues until we're in the relevant phase. let's keep a tidy worktop :-)

**Comment by rnllv** [comment]
@IanMayo, shall we reopen this?

**Comment by IanMayo** [comment]
yes please
