### ISSUE TITLE
Block of content not being parsed

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#481]
We aren't generating the `number4` target for Britain_Complex / Unit_anchors.

It is the `BottomLayer3` content provided here: https://github.com/DeepBlueCLtd/LegacyMan/blob/develop/data/Britain_Cmplx/unit_anchors.html#L937

Aah, that was because it wasn't being added to the shopping list.  The instance where it should have been called, instead linked to an external image.

When I fix that link ( [here](https://github.com/DeepBlueCLtd/LegacyMan/blob/develop/data/Britain_Cmplx/unit_anchors.html#L816) ) then the publish fails, because we are generating an invalid link.  It is using the word `topic` instead of the id of this concept.

So, we have a certain issue of link generation, and _maybe_ an instance of not picking up something from the shopping list.

![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/12b467c2-3aac-4f71-a8f0-9623add29ac0)

**Comment by robintw** [comment]
Ah yes, that's a silly mistake on my part. I'll see if I can fix it tonight, otherwise it'll be when I'm back from holiday.

**Comment by robintw** [comment]
Fixed in #482.
