### ISSUE TITLE
Headings in specific colors

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#485]
There are two headings that are present in particular shades.  Their HTML representation was horrendous, but I've simplified it to this:
https://github.com/DeepBlueCLtd/LegacyMan/pull/483/commits/3481abe22760b7b5485720520c8efefa99a74f71

When we convert them to DITA the output should look like this:
```
<p outputclass="h1">
  <ph outputclass="colorDarkBlue">This title is in blue</ph>
</p>
<p outputclass="h1">
  <ph outputclass="colorDarkBrown">This title is in blue</ph>
</p>
```

The `h1` processing is in placealready, as is the `ph` conversion. We just need to look for the specific color coding, and set the relevant output class.

**Comment by robintw** [comment]
Fixed in #489
