### ISSUE TITLE
Allow for ampersand in country folder name

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#486]
One folder contains the data for two countries.  It's not a fault in the data, it's two countries that are typically included together in the same sentence.

The ampersand is present in the folder name, as well as the country page filename, and the heading on the country page.

I think we've handled the last two instances, but not the first.

Mock content [here](https://github.com/DeepBlueCLtd/LegacyMan/pull/483/commits/278c3684f1693f7ebcbc2dd712814adcaa1a7103)

**Comment by robintw** [comment]
Fixed in #489
