### ISSUE TITLE
Headers in Tonals page

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#49]
Please confirm if I'm reading the `Tonals` page properly. 

Since it's a mix of tabular and cross-tabular data structure, it would be easier to parse this if my understanding of this page is proper.

One set consists of the following in the Propulsion table

* Cruise Plant
* Boost Plant
* Reduction Ratio
* Max SRPM
* Shaft x Blade
* Max Speed
* Range
* Av TPK

One set in the Class Summary part of tonals table
* Drive
* Mode
* Shaft x Blade
* R:R
* Range
* Av TPK (Guide)

Multiple rows in signatures section of tonals table
* Source
* Ratio/Freq
* Harmonics
* Remarks

One set in **SIGNATURE & CHARACTERISTICS** section of tonals table.
* Acoustic Signature
* Unique classifiers
* Aural

Also, please throw some light on how to read **`Commonly Detected Sources`**. **Note:** I think we've passed the point when this question was valid.

Also, can these attributes be expected to be in the original data as is?

**Comment by IanMayo** [comment]
Sure, happy to clarify.

I don't have easy access to the mock data right now. 

But, they aren't all types of tonal. The "Source, Ratio/Freq, HArmonics and Remarks" are the tonals.  The first two blocks you provided are both unit- level data representing Power (propulsion).

The last block is 3 sections of titled text blocks, each containing a few words, or a series of numbered paragraphs.

 To start with, let's just build up the table of tonals.  I'll look out to clarify the unit level data when I get chance (it was already on my to-do list :-) ).

**Comment by rnllv** [comment]
Okay, let me get started just with proper `Tonals` then: "Source, Ratio/Freq, Harmonics and Remarks".

Could you also look into the other two questions that I have?

```
Also, please throw some light on how to read Commonly Detected Sources.

Also, can these attributes be expected to be in the original data as is? Meaning can these attributes be hard coded?
```

**Comment by IanMayo** [comment]
> Also, please throw some light on how to read Commonly Detected Sources.

Rows of tonals, each with their preceding tonal-type. They tend to start with propulsion data, but the order of the others is less preditable.

> Also, can these attributes be expected to be in the original data as is? Meaning can these attributes be hard coded?

The table headers can be hard-coded. The tonal-types cannot be.  I may have some work to provide increased consistency across the tonal types, but this will be easier to understand once we have processing for it.

**Comment by rnllv** [comment]
Do you want any tests here, @IanMayo?

Say, don't  read any tonals without `Commonly Detected Sources`.

**Comment by IanMayo** [comment]
> Say, don't read any tonals without Commonly Detected Sources.

For now, I'd like that to be reported as a `discrepancy`.  That will let me check that there aren't any subtle mis-spellings.

I'll try to think of other instances of doing that, as they arise.

**Comment by rnllv** [comment]
Okay

**Comment by IanMayo** [comment]
I think we're past this now @rnllv 

Our mock data demonstrates the above patterns. Well, it should ;-)

Can we close it?

**Comment by rnllv** [comment]
Closing this as this issue has been outdated by recent changes.
