### ISSUE TITLE
A24 - content not captured

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#491]
For file A24 there is only an image in the DITA output.

This file is not being parsed from a `category listing`, but from an-in page link . So, it is just being processed as a generic page.

Inspect content/structure, reproduce in our data.

**Comment by robintw** [comment]
The key bits of information to have here will be the output of the links table (printed at the end of run 2 when you run in debug mode), which shows the shopping list of which parts of the page are being included.

**Comment by robintw** [comment]
I'm a bit confused about the difference between this and #494 - are they actually the same issue? It's possible that the fix for #494 fixes this too. Do you want to try it on site, and then if it isn't fixed you can expand this issue?

**Comment by IanMayo** [comment]
Ian to inspect onsite

**Comment by IanMayo** [comment]
File a24 being processed fine.
