### ISSUE TITLE
A25 & A26 - signatures table missing

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#494]
For files A25 & A26 we don't capture the signatures table

Investigate pattern, reproduce in mock content.

After a quick look, this seems related to the A24 layer issue. On each occasion, the `div` has just one child, an image with src "xxxxxx/image020.jpg" (it's the corporate logo).

Aah, but in A24 this layer _trails_ the content of interest.  Aah, it does in A25, too. In A26 it _leads_ the content matter.

I suggest when we are "looking for the first layer" we exclude divs that match the above.

Ok. We have leading and trailing blocks of content that block identification of the real first body of content in this PR:
https://github.com/DeepBlueCLtd/LegacyMan/pull/493

**Comment by robintw** [comment]
Fixed in #492.
