### ISSUE TITLE
Parse Single File not working as expected

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#495]
It's easy for me to spot single files the suffer from a problem.

I can insert specific IDs to track what is happening in the parse or publish phases.

But, my debug cycle is around 4 minutes.

We have the `parse_single_file` utility, but it currently appears to produce DITA for lots of files, and it appears to not produce DITa for the specified file.

Command: `python parser/parse_single_file.py data data/Wales_Composite/Wales_Composite.html`

Output:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/a6d434f7-2be5-4739-a725-7927e248aef6)

(Note: while we've had `parse_single_file` for a couple of weeks, I didn't have chance to use it in anger, due to a MS-Windows specific python library issue).

**Comment by robintw** [comment]
Yes, parse_single_file was broken - it was working when first implemented, but then we changed various things we were doing and it broke. I fixed it just now in #492.
