### ISSUE TITLE
Intermittent copying of Content/Images

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#496]
Hmm, for one category, in one country, the content/images folder is not getting copied over.  It's a country where all the units are defined in the country page, but the units themselves are in category-specific folders.  The source folder is named the same as others WA_Complex/Content/Images.

This failed for two runs, but has worked since.  

The issue only arose today, I presumed it was because fixes meant we were generating more target content.  But, the issue seems to have gone away again.

It seems worth a code inspection though - since it will be a pain if it comes back.  Hmm, though if/when it does come back I can insert debug lines to track progress.

**Comment by robintw** [comment]
Can you clarify exactly what "It's a country where all the units are defined in the country page, but the units themselves are in category-specific folders." means? An example giving a potential path to a country page, a path to the category page and a path to the unit-specific pages would be great (no need for any content, just a comment on this issue giving some example paths so I can see what path in the code this will be taking).

Also, is the `Content` page created but `Content/Images/` isn't? Or do both folders exist but the actual image files inside `Content/Images` don't?

**Comment by IanMayo** [comment]
Sorry it's vague @robintw .

> "It's a country where all the units are defined in the country page, but the units themselves are in category-specific folders." 

Sure, it's a country like `Spain` in our mock data. The `Spain/Spain.html` file contains the full table of units for the country.  But, there are enough units that they are actually stored in two sub-folders (Spain_Cmplx and Spain.Legacy).  So, these category folders don't contain an index/category table file - just the units.

That seemed relevant because the above pattern isn't very common, and we've only just introduced it in our mock data.

The issue doesn't arise in our mock data, so I can't give a sample.

The `Content` folder was generated, which contained some `.wav` files, but it's `Images` child folder wasn't created.  It should have contained about 12 images,  referenced by 4 unit pages.

**Comment by robintw** [comment]
Hmm, this is strange. I can't see how the `Content` folder can be copied, but without the `Images` subfolder. A few things to check that could help debug it:

- Is this happening with just one country?
- Can you check there are no strange permissions issues with the `Images` folder for that country?
- Can you search for a filename that should have been in that `Images` folder, and check to see if it has been accidentally copied to somewhere else? (This is the most likely thing I can think of - that it was copied, but it didn't cope with the structure of these different format countries properly, and copied the file to the wrong place)

**Comment by IanMayo** [comment]
Yes, it was just for one category within one country (like `Spain_Cmplx`).

Later that day it stopped failing.  There hadn't been a sofware update, but there is a _slim_ chance a correction to the source data fixed the issue - though I hadn't made changes to that nation.

Will do extra diagnostic steps next time fault occurs.

**Comment by IanMayo** [comment]
Issue hasn't re-occured.
