### ISSUE TITLE
Missing content in 100_unit_charlie.html

### ISSUE THREAD

**Issue by robintw** [DeepBlueCLtd/LegacyMan#499]
The conversion of `data/Spain.Legacy/100_unit_charlie.html` has missing content. The text `1.  Figure 1, above, shows system monitoring of` (and the continuation of that text) is missing from the output.

It seems like the last two images, plus the last bit of text aren't being converted. They are in sensibly arranged PageLayers/BottomLayers, so my suspicion is that they aren't linked to anywhere.

We should check the 'shopping list' and check this.

**Comment by robintw** [comment]
I've checked this, and the reason the last two bits of the page aren't being converted are because they aren't on the shopping list. It seems like this is correct: there are only links to `100_unit_charlie.html` and `#number3` for this page, so we end up with a shopping list of:

```
'Spain.Legacy/100_unit_charlie.html': {'##### First Page Layer',
                                                    'number3'},
```

We export both of those sections correctly, and don't export the final section that isn't linked from anywhere.

I think this is expected behaviour. Do you agree @IanMayo?

**Comment by IanMayo** [comment]
Aah yes.   In `Unit_Anchors` there are two sections that aren't referred to internally, but from a page of amplifying details.  `unit_charlie` is a modified `unit_anchors` but without the page of amplifying details. So, you are right, this section does not appear on the shopping list, and should not be present.

I _Think_ the correct way for me to handle this one the client data would be to inspect the page, and if the content shouldn't be there, then delete it in the source.

**Comment by robintw** [comment]
I agree. Are you happy for us to close this then?
