### ISSUE TITLE
Identification of tonal headers and attributes in Tonals page - Phase 1

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#50]
We'll be using a method (similar to the one described in #46) to identify Tonal headers and rows.

This is also based on the visual representation of the table, and involves metadata hardcoding.

We'll be explicitly checking for Source, Ratio/Freq, Harmonics, Remarks < td > column headers to be present in one row. 

Here's the method:
```
* Identify the tonal header: first < tr > which contains < td > elements with innerHTML as string literals "Source", "Ratio/Freq",  "Harmonics", and "Remarks" in the same order.
* Identify the `Tonal-Type` header: first < tr > following tonal header will be the first `Tonal-Type` < tr >  which might have optional < td > indicating the tonal-type,  say `Power Related` or `Auxiliary Sources` or `Transient Sources`. It MAY also have < strong > attribute
* Identify `Tonal attributes` under this `Tonal-Type`: < tr > with exactly four < td > elements 
* Keep collating the `Tonal attributes` under the previously identified `Tonal-Type` until reaching the next `Tonal-Type` header.
```

Assumptions:
* There will be only one Tonal table per tonal page under `PageLayer` div.

@IanMayo, please make corrections as necessary.

**Comment by IanMayo** [comment]
I'm pretty sure the tonals are always preceded by their `tonal-type` category.  Let's assume that - but also test to verify.  So the table rows are:
- 6 cells of propulsion cell headers
- 6 cells of propulsion cell values
- "commonly detected sources". [*]
- tonal headers
- first tonal type
- tonals

[*] I don't think we need to worry about the presence of this row or not. We're actually looking for the 4-column tonal headers - they mark the start of the tonals

**Comment by rnllv** [comment]
Yep, that's exactly how we've coded it now. Will be pushing it in sometime.

**Comment by rnllv** [comment]
This can be closed as any new changes to tonal extraction can be tracked via new issue.
