### ISSUE TITLE
Spain/Britain/Wales Pics issues

### ISSUE THREAD

**Issue by robintw** [DeepBlueCLtd/LegacyMan#500]
The new file checker found that `data/Spain/Spain_Pics.html` wasn't being converted at all. This was because all of the links to it were commented out.

I uncommented one of the links, and found that I now get errors from the DITA commands about it. That's because it doesn't have the normal structure of PageLayers etc - it is just a couple of divs and img tags without even a surrounding `<html>`, `<body>` and so on:

```
<div>Some placeholder text</div>
<img id="number3" src="Content/Images/oscill_c.jpg">
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
........
<div>Some other placeholder text</div>
<img id="number4" src="Content/Images/oscill_d.jpg">
```

**Comment by robintw** [comment]
Also, the same applies for `Britain_Pics.html`.

**Comment by robintw** [comment]
And also applies for `Wales_Pics.html`.

**Comment by IanMayo** [comment]
Ok.  We can remove those `pics` files.  We do separately have `pics` files with legitimate structure.

I'm happy to do this change in a branch off `develop`.
