### ISSUE TITLE
Table not exported in anchor_trans_fit.html

### ISSUE THREAD

**Issue by robintw** [DeepBlueCLtd/LegacyMan#503]
In `data/Britain_Cmplx/anchor_trans_fit.html` there is a table which isn't being exported. It's in a div that has a note above it saying:

> this is an example of a div of legitimate content that doesn't have an id, or fit into the BottomLayer/PageLayer model we see elsewhere

Do you know how often these occur? At the moment, we're excluding from processing any divs that don't have an ID. We could change that, but it may lead to selecting a load of content that we _don't_ want selecting. If these only occur a few times then it might be easier to just give them an ID, or even wrap them in a BottomLayer/PageLayer.

What do you think?

**Comment by IanMayo** [comment]
That is quite an unusual type of file.  If the checker flags it up, I'm happy to fix it by hand.

**Comment by robintw** [comment]
Brilliant, I was hoping you'd say that!

**Comment by IanMayo** [comment]
Ok, there do appear to be just two occasions where this happens.  I'll fix them by hand, by wrapping with some `BottomLayer` goodness.  Then I'll fix this/these files to match the structure of the real content - and we can validate that processing.

**Comment by IanMayo** [comment]
Done.
