### ISSUE TITLE
Allow empty table cells

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#523]
We have this content in `Britain_Complex\Phase_F.html`:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/f7d674eb-11b9-4e20-b953-c3eeb9f52de7)

Our DITA conversion omits the empty table cells:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/585b59dd-869e-4bf3-8a2a-0f0976a83c5f)

Oxygen and DITA-OT don't throw warnings for empty table cells, so I _don't_think_ we need to insert `&nbsp;`

**Comment by robintw** [comment]
Fixed in #524.
