### ISSUE TITLE
Deal with non-breaking spaces

### ISSUE THREAD

**Issue by robintw** [DeepBlueCLtd/LegacyMan#529]
A lot of our files have a large number of:

```
<p>&nbsp;</p>
```

in them, which are leaving space for things with specified top values to go in that space. In our conversion they just produce empty space.

We should deal with these sensibly - either:

- Just remove them (probably a good idea for now)
- Use them to try and work out where things with specified top values go (as mentioned in #518 )

**Comment by robintw** [comment]
Actually, in most normal files the nbsp's come outside of the BottomLayer or PageLayer divs - see, for example, `data/Spain_Cmplx/Phase_F.html`, so we aren't converting them. I suspect it is only pages where we have problems like in #518 where they appear in the middle of the PageLayer or BottomLayer divs.

**Comment by IanMayo** [comment]
Yes, most are to generate  vertical whitespace to generate the fake page effect, and we're don't process these.

Hopefully there are few enough within our processed content that I just move the relevant content into the right place.

**Comment by IanMayo** [comment]
Ian to check generated DITA content for lots of `&nbsp;` entries, and decide if this is a problem or not.

**Comment by IanMayo** [comment]
Broke, but now works again in Oxygen 26.0
