### ISSUE TITLE
Drop custom DTD schemas

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#535]
In this phase of the project we have been transitioning from custom XML schemas to standard/generic DITA ones.

Our `lman_parser.py` module still creates instances of `rich-collection.dtd`.  

We should switch to using `concept` schema (as we do for other page types), including dropping use of `related-pages`.  Our `quick-links` handling supercedes this.

The benefit of this is that it will remove a step when publishing in Oxygen.  We will not longer have to relax the rule allowing access to DTDs outside the current folder (`args-disable-security-links`)

**Comment by robintw** [comment]
Do you mean the concept schema, or the `reference` schema?

The generic pages are using the following schema definition at the moment:

```
'<!DOCTYPE reference PUBLIC "-//OASIS//DTD DITA Reference//EN" "reference.dtd">'
```

**Comment by IanMayo** [comment]
Sorry Robin, yes - we should adopt `reference`.
