### ISSUE TITLE
Introduce <short-description> content for major pages

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#537]
Our top level tiles can show supporting descriptions, like this:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/43b2c376-bca3-47b3-ad20-3adec1b73e1c)

It would be tidiest if this content was taken from the source documents.

In the generated DITA, this is presented like this, outside the body content:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/6c4b3800-503d-498f-8784-386cb50159b7)

One solution is for me to insert non-visible divs with and id of `short-description` in the content, and for this to be pulled through in the generic page parser.  Aah, I guess we also need to explicitly exclude these divs from our `div-finder`.  I guess we should always ignore divs with `style="visibility: hidden"`

## Update:
data changes implemented here: https://github.com/DeepBlueCLtd/LegacyMan/pull/538

**Comment by robintw** [comment]
Fixed in #544
