### ISSUE TITLE
Images not captured

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#547]
In file `France / FRA_A27_Unit.html` 3 images are provided after the table for the `BottomLayer`, through their `top` values cosmetically put them before the table:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/493846c2-34b0-4b44-b339-b08ab75e211a)

But, they don't get picked up at all by the parser:
![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/cb7b9b08-f093-4a33-a481-0b91ee349d60)

**Comment by robintw** [comment]
Fixed in #553.
