### ISSUE TITLE
Ensure url arguments to the `parser` module are hardened

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#55]
HTML pages have *nix urls (forward-slash as the path separator), where as Windows systems use backward-slash as path separator.

Mixing these two path separators might lead to `urljoin` method returning unexpected value and the program crashing.

Ensure arguments are hardened before being passed to sub-systems.

**Comment by rnllv** [comment]
@IanMayo to test various scenarios on Win system.

Let parser be in drive D, and data be in drive E

1. Call the parser with absolute windows path in E:

Let the parser and data be in the same drive

2. Call the parser with absolute windows path of the data directory
3. Call the parser with relative windows path of the data directory

Try the 3 cases above with forward slash (/) instead of backslash.

**Comment by IanMayo** [comment]
I'm on a VM that looks like this:
* The `c:` partition is almost full
* The `d:` partition is a mock DVD drive
* I have an `e:` partition with 450Gb of space on it.
* the data and code are on `e:`.  They aren't moving anywhere, nor do I want/need them to.

**Comment by IanMayo** [comment]
I'm closing this @rnllv . We don't need an enduring, versatile solution for the `LegacyMan` project - it is just to be used for this one parsing venture.
