### ISSUE TITLE
Images from `_pics.html` page not captured.

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#551]
The file `FR_Charlie_Pics.html` include several target blocks of content, all linked to from `fr_100_unit_charlie.html`

Well, it looks like the target blocks are picked up and ported over, but they do not contain the expected image.  Aah, the DITA validator doesn't complain about missing target links.  So, I see we are porting the blocks over, and giving them the correct anchor id, but the image content (or text content for `#number5`) aren't present.

**Comment by robintw** [comment]
Fixed in #553.
