### ISSUE TITLE
Idea: Store shopping list in file for use in single-file processing and/or main processing

### ISSUE THREAD

**Issue by robintw** [DeepBlueCLtd/LegacyMan#557]
I had an idea late last night, and I'd like to see what you think of it.

After completing Run 1 (looking for links etc), we could store the 'shopping list' dictionary that we produce in a file (probably as JSON). We could then use this file in various situations:
- When running processing for a single file, we could use this _instead_ of having to do Run 1. This would significantly increase the speed of running for a single file, and should mean we can do it so that only one output file gets created. It should simplify the 'run a single file' code to just extracting the relevant entry from the dictionary and running `process_generic_file`.
- We could also use this when we process all files, and have a command-line parameter that says whether to run Run 1 or not. If we choose not to do Run 1, then we just used the saved shopping list from last time. This means that any changes to links won't be picked up, and the shopping list won't be updated - but it would also speed things up significantly when we're iterating.

What do you think?

This should be a fairly simple thing to implement. The big question is where we should store the JSON file containing the shopping list. Do we have write access to the input (`data`) directory? If so, we could store it there. If not, we'll have to think of somewhere else.

**Comment by IanMayo** [comment]
Good plan @robintw .

I'd rather not put data in the input folder. I'm happy with the current working folder, and we add the file to .gitignore.

**Comment by IanMayo** [comment]
Done. Working well.
