### ISSUE TITLE
Check the location of `target` directory when calling the parser with absolute paths with drive components

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#57]
The target folder is created with reference to the current working directory. So, if absolute paths are used, it'll be created in the drive referenced in the absolute path.

This might cause issues with existing files/directories of the same name. Target directory and file name should be supplied as arguments to the parser.

**Comment by IanMayo** [comment]
One day - we may have enough complexity in the generated data that we need to specify a target directory.

Let's address this issue when we get to that point.
