### ISSUE TITLE
Copy `contents` folder for generic files

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#592]
We have a folder `Introduction` which only contains generic files.

The `contents` folder isn't copied over for this folder, which suggests that we only copy `Contents` folder for files that are receiving special processing.

The issue can be seen as a `publish` error in PR https://github.com/DeepBlueCLtd/LegacyMan/pull/585

**Comment by robintw** [comment]
The reason this folder isn't being copied is because it is called `Contents` and the equivalent folder for all other places in the data is called `Content`. Is this just a typo? Or should we be accepting any folder that looks like `Content` or `Contents` or similar?

**Comment by IanMayo** [comment]
Oh, thanks for that @robintw .  I'll have to double-check what's happening in the target content.  (It's most probably my mistake)

**Comment by IanMayo** [comment]
Yes @robintw - you were quite right.  The folder title was wrong.
