### ISSUE TITLE
Also need quick links on ImageLinksTable page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#593]
Some countries start with an `ImageLinksTable` page.

We need to support QuickLinksTable collections on these pages.

~~(I'll create some mock data, and push to develop)~~ No need, `Britain1.html` has an image links table already.

**Comment by robintw** [comment]
I haven't come across an ImageLinksTable before. Is this just an additional QuickLinks table, but it happens that all of the links have images as well? Do we just want to extract the hrefs from the links in it, and put them in the related-links section, as we do with the QuickLinksTable links?

**Comment by IanMayo** [comment]
> I haven't come across an ImageLinksTable before.

Oh, I didn't realise. For some nations, where there are a lot of records of data, the country page is collection of floating images, one per category - and these link to the relevant category page.

But, it's a nightmare to process these floating images.  So, I created an `ImageLinksTable` in each page, that presents the images/links in an easy to find, easy to process table.

The processing for the ImageLinksTable works fine, it's just that also need to handle `QuickLinksTable` if it appears on these pages. We just need to create the `related-links` like we do for other `QuickLinksTable` instances.

**Comment by robintw** [comment]
Ah, that makes sense. I'll get on that this evening.
