### ISSUE TITLE
Trailing content after category table

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#600]
At least one category table has several paragraphs of trailing content (in the same parent div).

There isn't another obvious page where I could manually move this content to.

We should parse it, and include it after our converted category table.

**Comment by robintw** [comment]
Is this replicated anywhere in the mock data at the moment? If not, could you replicate some simple version of it and then I can have a go at coding this up.

**Comment by IanMayo** [comment]
Present in mock content here: https://github.com/DeepBlueCLtd/LegacyMan/pull/602/files

**Comment by IanMayo** [comment]
@IanMayo  to check that R-R category page includes extra content.

**Comment by IanMayo** [comment]
Tested and working.
