### ISSUE TITLE
Parser trips over sanitising file in root folder

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#616]
In #615 the parser falls over when trying to sanitise a filename (`welcome.html`) in the root folder.

![image](https://github.com/DeepBlueCLtd/LegacyMan/assets/1108513/5acd4ebe-b4fa-43f1-8508-69075f6acbc4)

I think there are least two successive bugs to fix in `sanitise_filename`.

This issue can be experienced in the branch for PR #615

**Comment by robintw** [comment]
Fixed in #615.
