### ISSUE TITLE
Alternate test strategy for LegacyMan Parser

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#79]
Hello @rnllv - the tests are valid, and I can see they help us out.

But, I'd like us to discuss/consider a different strategy.  I honestly don't know if this alternate strategy is better or not.  Let me explain it.  This PR uses a test to verify a method works as expected.

But, we're going to throw these methods away, eventually.

How about we try another strategy?   We run the full `parse` on the `mock` data, then we test the results - whether things are, or aren't present in the output JSON.

So, when I encounter something "breaking" in the real data, I reproduce it in the "mock" data, and write a (failing) test that highlights the issue.  You then modify the `parse` code to fix the test.

Hmm, at some point, we're going to switch to writing to DITA, but right now I think it may be worth running DITA and JSON exports in parallel - so the range of entities present in the JSON grow with the range of entities in DITA.

I'm not quite sure how the above will suit the thing we're testing here.  It will probably fail.  We can't test for the absence of Britain (`../Britain/`), since we currently import Britain into Europe, too.  That's a silly aspect of the mock data  - so I think it would be for me to modify (fix) the mock data.

What are your thoughts on all that?

_Originally posted by @IanMayo in https://github.com/DeepBlueCLtd/LegacyMan/issues/78#issuecomment-1357702369_

**Comment by rnllv** [comment]
I believe this will complement our test strategy, @IanMayo. 

We can define some test cases like
* Country A should have 2 units.
* Unit A of country A should have 10 tonals, and all remarks should be same.

Another advantage I see is that if we decouple the test logic and test payload, clients can come up with their own test payload and test the parsing on the actual data.

**Comment by rnllv** [comment]
>whether things are, or aren't present in the output JSON.

The downside is that this won't be able to test all possible issues (unless we come up with a detailed test payload which is akin to clients parsing the entire data set manually)

**Comment by IanMayo** [comment]
> we won't be able to test all possible issues

Agreed.  It will focus on specific issues, as we encounter them.
