### ISSUE TITLE
DITA-OTT dependencies

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#81]
@IanMayo to check if system is compatible for DITA-OTT application.

These commands should do. Please obfuscate the path outputs.
```
java --version
where javac  :: Check if jdk is available
where java   :: Checks for java runtime
```

`where` is MS Windows equivalent to Linux's `which`

**Comment by IanMayo** [comment]
Java wasn't installed. Installing v18 JRE.  This article says only JRE is required: https://www.dita-ot.org/dev/topics/prerequisite-software.html#:~:text=DITA%2DOT%204.0%20is%20designed,com%2Fjava%20under%20commercial%20license.

(Note: I fully expect that Oxygen will include a JRE anyway)

**Comment by IanMayo** [comment]
JRE 18.x installed & verified
