### ISSUE TITLE
List of initial `parsed_json` tests

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#84]
@IanMayo, please provide an initial list of tests to be executed on the parsed json file.

**Comment by rnllv** [comment]
PROPOSED_TEST_1: Would it be meaningful to have a test like check the count of classes for each country? 

```
{
    "France": 25,
    "Britain": 40,
    "Spain": 22,
    "Belgium": 20
}
```

**Comment by IanMayo** [comment]
Drop this, we're having to take a more streamlined approach.
