### ISSUE TITLE
Check why `unit_d` is not reflecting in France

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#85]
Mock html has defined 4 units for France

![image](https://user-images.githubusercontent.com/77854924/208930834-6f34330a-4de9-4bca-aa9b-686156d275e5.png)

Parsed json only lists 3 for France

![image](https://user-images.githubusercontent.com/77854924/208930905-fddf80ac-b1bf-4274-ad66-61dc051ab03c.png)

**Comment by rnllv** [comment]
This looks to be expected behaviour due to the solution implemented for [this issue](https://github.com/DeepBlueCLtd/LegacyMan/issues/56).

![image](https://user-images.githubusercontent.com/77854924/208935311-111308b2-282a-43bc-a985-e64ee2196a71.png)

@IanMayo, just wanted to confirm if this indeed valid behaviour, or should we be handling this just like how we'll be handling multi-row remarks?

**Comment by IanMayo** [comment]
Yes - we should _eventually_ include unit_d, once we handle the `rowspan` content.

**Comment by rnllv** [comment]
Okay. Is it just going to be the *Power* and *RR* columns that may be merged, or should we check the same for other columns as well?

**Comment by IanMayo** [comment]
I didn't see a pattern, so it appears any column could be merged.  Aah, except for the first one - that's the unique identifier.

**Comment by rnllv** [comment]
@IanMayo, also check if the tables have `colspan` contents in the data section. I see one possibility where they might merge multiple columns to indicate *non-availability* or *non-applicability* (N.A.)

If there're such rows, then we'll need to handle them as well.

**Comment by rnllv** [comment]
I had removed the `Too few properties` exception. I believe we should retain it to make the processing sturdier.
