### ISSUE TITLE
URL Check - Spain

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#87]
This is the url for Spain
https://deepbluecltd.github.io/LegacyMan/data/Spain1/Spain.html

Should this be .../Spain/Spain1.html as that's the pattern seen for France and Narnia?

**Comment by IanMayo** [comment]
I know what you mean.  But, there are lots of inconsistencies like this in the real data, so it's right we have some variety, to prevent making assumptions about how we can parse the data.

**Comment by rnllv** [comment]
Ahh okay :)
Will close this then.
