### ISSUE TITLE
Extract power details from classes

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#96]
Store power details as part of phase 2 parsing.

![image](https://user-images.githubusercontent.com/77854924/214615678-51ab71ee-7700-400a-8c8a-04cd9dce4568.png)

**Comment by rnllv** [comment]
@IanMayo, we're already parsing *Power* details when we process *Class/Units* from the highlighted green box in the below screenshot

![image](https://user-images.githubusercontent.com/77854924/214616636-bcf24d56-19d9-47f0-ab2c-c6bc268bcd06.png)

Are we referring to the *Propulsion* attributes found only in Tonals page?

![image](https://user-images.githubusercontent.com/77854924/214617310-7372dbb0-4965-4cca-9432-4d5c2df0a105.png)

**Comment by IanMayo** [comment]
It's the same data.  The top image shows power for 4 different classes of unit.  For the top 3 (a, b, c) we only have the value in this table. But, for (d) we have a link to the more detailed page - and we should take the Power from that page.

For the future, it is the same for some of the other metadata - where we may see a summary on the country page, but more detail on the class page.

I _guess_ we could store the value from the country page, and overwrite it if we have more detail from a dedicated `class` page.
