### ISSUE TITLE
Parsing unit and quantity for DITA

### ISSUE THREAD

**Issue by rnllv** [DeepBlueCLtd/LegacyMan#99]
@IanMayo, kindly check if we have to parse quantities and units from attribute values. 

Suppose if an attribute value is 12 ltr/hr, should the parser be aware that the quantity here is **12** and unit *ltr/hr*.

**Comment by IanMayo** [comment]
Yes, we should break down values and units.

**Comment by rnllv** [comment]
@IanMayo, are the units used in mock data same as the ones used in real data? Or are units also *masked* as per #6?

**Comment by rnllv** [comment]
I suspect it's not as I see *hrs* (time) as unit for a **BHP** (engine power) field. If yes, I believe we should defer this issue until we find a solution for #6.

Please correct me if wrong.

**Comment by IanMayo** [comment]
Defer. We're a long way from this.
